# Data preprocessing

In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
data_path = "../data/btc_onchain_daily.csv"

In [37]:
data = pd.read_csv(data_path)

data

,date,price_usd,active_addresses,tx_count,hash_rate,supply_current,fee_usd,difficulty,miner_revenue_usd,estimated_transaction_volume_usd
0,2015-01-01,314.776472,145765.0,60177.0,3.333450e+05,1.367561e+07,2989.225322,4.064096e+10,1.519572e+06,2.591460e+07
1,2015-01-02,315.942732,212932.0,83050.0,3.333450e+05,1.367974e+07,4047.380221,4.064096e+10,1.475784e+06,4.127515e+07
2,2015-01-03,285.647310,241755.0,81404.0,3.272842e+05,1.368379e+07,4357.131514,4.064096e+10,1.586907e+06,9.035606e+07
3,2015-01-04,263.334575,235011.0,82769.0,3.474869e+05,1.368809e+07,7189.970880,4.064096e+10,1.632203e+06,8.259991e+07
4,2015-01-05,275.003852,242515.0,95721.0,3.151626e+05,1.369199e+07,4615.535489,4.064096e+10,1.202039e+06,6.842295e+07
...,...,...,...,...,...,...,...,...,...,...
4140,2026-05-03,78649.173289,583469.0,596099.0,1.000953e+09,2.002414e+07,223261.979237,1.324720e+14,3.669183e+07,1.787557e+09
4141,2026-05-04,79826.107817,722079.0,567474.0,9.811977e+08,2.002461e+07,226417.689402,1.324720e+14,3.685130e+07,7.880460e+09
4142,2026-05-05,80936.754825,721256.0,589261.0,9.877829e+08,2.002508e+07,229573.399568,1.324720e+14,3.701078e+07,8.837710e+09
4143,2026-05-06,81364.620129,NaN,531510.0,9.285159e+08,NaN,232729.109734,1.324720e+14,3.717025e+07,7.722302e+09
4144,2026-05-07,NaN,NaN,NaN,NaN,NaN,232729.109734,1.324720e+14,3.717025e+07,7.722302e+09

## Duplication data

In [38]:
data_dup = data[data.duplicated(keep='first')]

data_dup

Empty DataFrame
Columns: [date, price_usd, active_addresses, tx_count, hash_rate, supply_current, fee_usd, difficulty, miner_revenue_usd, estimated_transaction_volume_usd]
Index: []

## Missing data

In [39]:
data_missing_count = data.isnull().sum()
print(data_missing_count)

date                                0
price_usd                           1
active_addresses                    2
tx_count                            1
hash_rate                           1
supply_current                      2
fee_usd                             0
difficulty                          0
miner_revenue_usd                   0
estimated_transaction_volume_usd    0
dtype: int64

In [40]:
data_with_na = data[data.isna().any(axis=1)]

data_with_na

,date,price_usd,active_addresses,tx_count,hash_rate,supply_current,fee_usd,difficulty,miner_revenue_usd,estimated_transaction_volume_usd
4143,2026-05-06,81364.620129,NaN,531510.0,9.285159e+08,NaN,232729.109734,1.324720e+14,3.717025e+07,7.722302e+09
4144,2026-05-07,NaN,NaN,NaN,NaN,NaN,232729.109734,1.324720e+14,3.717025e+07,7.722302e+09

- Drop na column

In [41]:
data_dropna = data.dropna()

data_dropna.shape

(4143, 10)

- Round the values to 0 decimal (like integer)

In [42]:
float_cols = data_dropna.select_dtypes(include=['float64']).columns
print(float_cols)

data_dropna[float_cols] = data_dropna[float_cols].round(0).astype('int64')

data_dropna.head(5)

Index(['price_usd', 'active_addresses', 'tx_count', 'hash_rate',
       'supply_current', 'fee_usd', 'difficulty', 'miner_revenue_usd',
       'estimated_transaction_volume_usd'],
      dtype='str')

,date,price_usd,active_addresses,tx_count,hash_rate,supply_current,fee_usd,difficulty,miner_revenue_usd,estimated_transaction_volume_usd
0,2015-01-01,315,145765,60177,333345,13675615,2989,40640955017,1519572,25914596
1,2015-01-02,316,212932,83050,333345,13679740,4047,40640955017,1475784,41275152
2,2015-01-03,286,241755,81404,327284,13683790,4357,40640955017,1586907,90356063
3,2015-01-04,263,235011,82769,347487,13688090,7190,40640955017,1632203,82599915
4,2015-01-05,275,242515,95721,315163,13691990,4616,40640955017,1202039,68422951

## Save preprocessed data

In [44]:
pre_data= "../data/preprocessed/btc_onchain_daily_preprocessed.csv"
data_dropna.to_csv(pre_data, index=False)

## Oke, done